name: weather_api_openweathermap
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: any
  json_serializable: any
  lints: ^2.0.0
  test: ^1.6.1
